### ISSUE TITLE
Design: wybór OFICJALNY / TESTOWY

### ISSUE THREAD

**Issue by Marahin** [Marahin/mirkots-client#12]
Dodanie pod formularzem logowania małego okieneczka z listą serwerów do wyboru. Domyślnie zaznaczony "OFICJALNY", drugi serwer do wyboru - "TESTOWY". 
Oficjalny łączy się na mirkots.pl, testowy zaś - gm1.gimb.us:7173.

**Comment by mayoseh** [comment]
wystarczy zmieniać port -> 7171 dla oficjalnego, 7173 dla testowego, ip może pozostać mirkots.pl
