### ISSUE TITLE
Glitch w Opuszczonej Kopalni

### ISSUE THREAD

**Issue by Marahin** [Marahin/mirkots-client#2]
Forum: http://forum.mirkots.gimb.us/viewtopic.php?f=3&t=334

Podobno spowodowany przez deski na wejściu.

**Comment by tehftw** [comment]
To błąd z papryczką jalapeno. Usuń to, ja zaraz dodam normalnego issue.

W kopalni jest okej.

**Comment by Marahin** [comment]
Pomyłka, błąd dotyczy #4
