### ISSUE TITLE
OSX - Crash po wylogowaniu

### ISSUE THREAD

**Issue by Shentang** [Marahin/mirkots-client#27]
Assertion failed: (px != nullptr), function operator->, file /Users/rabusek1/mirkots2/mirkots-client/src/framework/../framework/stdext/shared_object.h, line 90.
Abort trap: 6

Nie wiem czy to nie fix poprzedniego crasha #14 czasem - bo wcześniej działało.

**Comment by Marahin** [comment]
Zostało poprawione w https://github.com/Marahin/mirkots-client/commit/77396b571462237699f7b6e22f44c6bab0d6546b - masz skompilowaną nieaktualną wersję sprzed wydania mastera (kompilowałeś z development, a poprawka weszła po merge'u na master).

**Comment by mayoseh** [comment]
crashowało też na windowsie, zostało naprawione przy ostatniej poprawce, było to związane z poprawką od #10, na masterze jest wszystko działające. Jeśli błąd się powtórzy po skompilowaniu najnowszej wersji - powiadom o tym.
