### ISSUE TITLE
OSX - Plik dat nie wczytuje sie.

### ISSUE THREAD

**Issue by Shentang** [Marahin/mirkots-client#6]
Plik .dat z tibii 10.77 nie wczytuje mi sie na OSXie po kompilacji. 

<img width="769" alt="zrzut ekranu 2016-02-21 o 01 14 57" src="https://cloud.githubusercontent.com/assets/17368229/13200026/8c064cba-d838-11e5-9b5b-f97cb9044ff5.png">

**Comment by mayoseh** [comment]
pliki .dat i .spr w mirkots kliencie są inne niż te oryginalne z tibii 10.77 - czy były sprawdzane oba warianty?

**Comment by mayoseh** [comment]
Udało mi się zreplikować ten error na Windowsie.
Aby go naprawić na Windowsie należy pobrać pliki beta klienta ze strony mirkots.pl a następnie przekopiować tibia.dat oraz tibia.spr z pobranego klienta do nowo skompilowanego klienta.
Prawdopodobnie ta metoda zadziała też dla OSX.

**Comment by Shentang** [comment]
Zamykam, zafixowane
